### PR TITLE
Add github CI workflow

### PR DESCRIPTION
**Pull request by bitraid**
A CI workflow that builds using {g++,clang++}-{glibc,musl}, and uploads the artifacts.

### CODE REVIEW

**Comment by tosiara** [comment]
To avoid additional supply chain attack vector, I'd prefer to run this CI using a docker images that Motion Project has full control of. Currently, this action job depends on two thirdparty Github accounts: "jirutka" and "webiny"

**Comment by bitraid** [comment]
It only uses one 3rd party action from jirutka (there is no action from webiny).
I have checked the code, and the information below form its readme, seems to be true:
>The whole environment, all packages, are always installed directly from the Alpine Linux’s official repositories using [apk-tools](https://gitlab.alpinelinux.org/alpine/apk-tools/) (Alpine’s package manager). There’s no intermediate layer that tends to lang behind with security fixes (such as Docker images). — You might be thinking, isn’t that slow? No, it’s faster than pulling a Docker image!

If you want to be 100% safe, you could fork it and use that (to avoid docker).

**Comment by Mr-Dave** [comment]
@tosiara Is there anything that can be retained of this?  (I'm open to reverting if needed)

**Comment by bitraid** [comment]
- You could remove the 3rd party action (and musl support), by applying this patch:
```diff
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index e52437c..0daad85 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,54 +30,18 @@ jobs:
       fail-fast: false
       matrix:
         cxx: [g++, clang++]
-        libc: [glibc, musl]
         include:
           - cxx: g++
             cc: gcc
           - cxx: clang++
             cc: clang
-          - libc: glibc
-            shell: bash
-          - libc: musl
-            shell: alpine.sh {0}
-
-    defaults:
-      run:
-        shell: ${{ matrix.shell }}
 
     steps:
       - name: Set up Ubuntu
-        if: matrix.libc == 'glibc'
         run: |
           sudo apt-get update
           sudo apt-get install -y autopoint pkgconf gettext libcamera-dev libopencv-dev libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev libwebp-dev libmicrohttpd-dev libmariadb-dev libasound2-dev libpulse-dev libfftw3-dev
 
-      - name: Set up Alpine
-        if: matrix.libc == 'musl'
-        uses: jirutka/setup-alpine@master
-        with:
-          branch: edge
-          packages: >
-            build-base
-            clang
-            file
-            autoconf
-            automake
-            gettext-dev
-            libtool
-            libzip-dev
-            jpeg-dev
-            v4l-utils-libs
-            libcamera-dev
-            opencv-dev
-            ffmpeg-dev
-            libmicrohttpd-dev
-            sqlite-dev
-            mariadb-dev
-            alsa-lib-dev
-            pulseaudio-dev
-            fftw-dev
-
       - name: Checkout source
         uses: actions/checkout@main
 
@@ -99,6 +63,6 @@ jobs:
       - name: Upload artifact
         uses: actions/upload-artifact@main
         with:
-          name: motionplus-${{ matrix.cc }}-${{ matrix.libc }}-${{ github.sha }}
+          name: motionplus-${{ matrix.cc }}-${{ github.sha }}
           path: src/motionplus
           compression-level: 9
```
- Or, you could fork `jirutka/setup-alpine` and `webiny/action-post-run`, and:
make this change to the workflow:
```diff
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index e52437c..f99770e 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -54,7 +54,7 @@ jobs:
 
       - name: Set up Alpine
         if: matrix.libc == 'musl'
-        uses: jirutka/setup-alpine@master
+        uses: Motion-Project/setup-alpine@master
         with:
           branch: edge
           packages: >
```
and this change to your `setup-alpine` fork:
```diff
diff --git a/action.yml b/action.yml
index 026c21d..43cfb98 100644
--- a/action.yml
+++ b/action.yml
@@ -88,6 +88,6 @@ runs:
       working-directory: ${{ github.action_path }}
       shell: bash
 
-    - uses: webiny/action-post-run@3.1.0
+    - uses: Motion-Project/action-post-run@master
       with:
         run: sudo "${{ steps.setup.outputs.root-path }}"/destroy.sh
```

**Comment by tosiara** [comment]
@Mr-Dave do we really want to support Alpine builds? Over the past many years we have been providing only debs

**Comment by bitraid** [comment]
> @Mr-Dave do we really want to support Alpine builds? Over the past many years we have been providing only debs

If I may comment on this: It is not specific to Alpine, but rather on musl based distros. Also, because the Alpine edge channel is used, more recent versions of the dependencies are tested, something that would catch bugs like #146. Even if you officially only provide debs, I would guess that you'd want the project to be able to compile and run on as many targets as possible. After all, the purpose of the CI is not for providing (release) builds, but for testing the changes on different compilers/libraries/environments.

**Comment by tosiara** [comment]
Running just ci to see if there are any build issues is fine, but in that case we should not retain any executable artifacts

**Comment by bitraid** [comment]
> Running just ci to see if there are any build issues is fine, but in that case we should not retain any executable artifacts

Fair enough: #151

**Pull request merged**
